add jscs. update deps. clean up prepush hook

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,30 +1,19 @@
 #!/bin/sh
 
-bold=`tput bold`
 red=`tput setaf 1`
 green=`tput setaf 2`
 reset=`tput sgr0`
-error=${bold}${red}
-success=${bold}${green}
-errorBanner="${error}-------------------------------------------------
-PRE-PUSH FAILED
--------------------------------------------------\n${reset}"
-successBanner="${success}-------------------------------------------------
-PRE-PUSH OK
--------------------------------------------------\n${reset}"
 
-# commit hook for JShint
-gulp lint --prepush=true
-lintProcess=$?
+# run npm prepush command
+npm run prepush
 
-# now output the stuff
-if [[ $lintProcess == 1 ]]; then
-    echo "\n${errorBanner}"
-    if [[ $lintProcess == 1 ]]; then
-        echo "${error}• JSHint errors found.${reset}\n"
-    fi
-    exit 1
+if [ $? -eq 0 ]
+then
+    echo "${green}------------------------------"
+    echo "pre-push success"
+    echo "------------------------------${reset}"
 else
-    echo "\n${successBanner}"
-    exit 0
+    echo "${red}------------------------------"
+    echo "pre-push failure"
+    echo "------------------------------${reset}"
 fi
